name: Run Python Script on Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Run Python Script
      run: python test.py ${{secrets.AWS_USERNAME}} ${{secrets.AWS_PASSWORD}}
